### ISSUE TITLE
GAN models

### ISSUE THREAD

**Issue by alelordelo** [JacopoMangiavacchi/SwiftCoreMLTools#8]
Hi, amazing to see an initiative for ML trainning on Mac! ; )

Would it be possible to export a model from Pytroch to coreml, and then train (not inference) this coreml model on a mac?

**Comment by JacopoMangiavacchi** [comment]
Yes it is possible with the regular CoreMLTools python package. But not all layers are trainable on CoreML.  Look at the CoreMLTools documentation and source code on the official repo.

**Comment by alelordelo** [comment]
thanks Jacopo, 

I didn't get the notification by email so only read your reply now! 🙃
 
 AFIAK CoreMLTools only allow:
  PyTorch -> CoreML (device inference)
  
  And not 
  PyTorch -> CoreML Xcode trainning
  
  Am I wrong?

**Comment by JacopoMangiavacchi** [comment]
You can enable on device training for a limited type of layers with CoreML.  This is usually intended for head personalization or transfer learning scenarios but technically you can train a full model (with several limitations again).  Alternatively you can use the ML Compute framework that support training on more layers type.  Take a look at apple documentations for both ML Compute and CoreMLTools

**Comment by alelordelo** [comment]
thanks Jacopo!

Do you know any tutorial on how to train a CoreML model in ML Compute?

Apple documentation is zero, and I didn't find anything on the web....

**Comment by JacopoMangiavacchi** [comment]
ML Compute is a different set of API than Core ML but they are both wrappers on top of the same apple internal frameworks for ml acceleration.  I simply played a bit with ML Compute, I'm not an expert and I've never really used it in production, but I wrote this tutorial :

https://towardsdatascience.com/use-apple-new-ml-compute-framework-to-accelerate-ml-training-and-inferencing-on-ios-and-macos-8b7b84f63031
